# Generated by Django 5.2.14 on 2026-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brands/logos/'),
        ),
    ]
