# Generated by Django 5.2.14 on 2026-05-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support/'),
        ),
    ]
