# Generated by Django 5.2.14 on 2026-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportcontent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='نام برند')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('about_text', models.TextField(verbose_name='متن درباره ما')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='تصویر درباره ما')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='شبکه\u200cهای اجتماعی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
