# Generated by Django 5.2.14 on 2026-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_faqcategory_alter_supportcontent_type_faqitem_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='مبلغ جایزه دعوت از دوستان (تومان)'),
        ),
    ]
