# Generated by Django 5.2.14 on 2026-05-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
