# Generated by Django 5.2.14 on 2026-05-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'درآمد'), ('WITHDRAWAL', 'برداشت'), ('DEPOSIT', 'شارژ کیف پول'), ('BONUS', 'پاداش'), ('REFUND', 'بازگشت')], max_length=20),
        ),
    ]
