# Generated by Django 5.2.14 on 2026-05-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driverprofile_referral_code_and_more'),
        ('trips', '0003_trip_driver_car_image_trip_installation_verified_and_more'),
        ('wallets', '0002_wallet_total_earnings_bankaccount_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='drivers.driverprofile')),
                ('referred_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_rewards', to='drivers.driverprofile')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.trip')),
            ],
        ),
    ]
