# Generated by Django 5.2.14 on 2026-05-18 14:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_clientprofile_brand_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('50000'), help_text='نرخ ساعتی پایه (تومان)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع خودرو',
                'verbose_name_plural': 'انواع خودرو',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.CharField(blank=True, max_length=4)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('plate_number', models.CharField(help_text='شماره پلاک', max_length=20, unique=True)),
                ('plate_image', models.ImageField(blank=True, upload_to='vehicles/plates/')),
                ('license_number', models.CharField(blank=True, help_text='شماره گواهینامه یا برگه ثبت خودرو', max_length=20)),
                ('banner_max_width_cm', models.PositiveIntegerField()),
                ('banner_max_height_cm', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.driverprofile')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
