# Generated by Django 5.2.14 on 2026-05-08 02:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('DRIVER', 'Driver')], default='CLIENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_type', models.CharField(choices=[('REAL', 'حقیقی'), ('LEGAL', 'حقوقی')], default='REAL', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('national_id', models.CharField(blank=True, help_text='برای حقیقی: کد ملی ۱۰ رقمی', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد ملی باید ۱۰ رقمی باشد.')])),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('national_economic_code', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clients/avatars/')),
                ('id_or_registration_copy', models.ImageField(blank=True, null=True, upload_to='clients/kyc_docs/')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('kyc_reject_reason', models.TextField(blank=True, null=True)),
                ('kyc_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand_name', models.CharField(blank=True, max_length=120, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='clients/brand_logos/')),
                ('brand_banner', models.ImageField(blank=True, null=True, upload_to='clients/brand_banners/')),
                ('brand_description', models.TextField(blank=True, null=True)),
                ('primary_ad_image', models.ImageField(blank=True, null=True, upload_to='clients/ads/primary_images/')),
                ('primary_ad_banner', models.ImageField(blank=True, null=True, upload_to='clients/ads/primary_banners/')),
                ('advertising_description', models.TextField(blank=True, null=True)),
                ('advertising_license_copy', models.ImageField(blank=True, null=True, upload_to='clients/ads/licenses/')),
                ('is_advertising_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='drivers/avatars/')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id_image', models.ImageField(blank=True, null=True, upload_to='drivers/id_cards/')),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to='drivers/selfies/')),
                ('license_copy', models.ImageField(blank=True, null=True, upload_to='drivers/licenses/')),
                ('license_expire_date', models.DateField(blank=True, null=True)),
                ('vehicle_document_copy', models.ImageField(blank=True, null=True, upload_to='drivers/vehicle_docs/')),
                ('vehicle_insurance_copy', models.ImageField(blank=True, null=True, upload_to='drivers/insurance_docs/')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('kyc_reject_reason', models.TextField(blank=True, null=True)),
                ('kyc_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=4, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_plate_image', models.ImageField(blank=True, null=True, upload_to='drivers/plates/')),
                ('license_number', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='drivers/brand_logos/')),
                ('brand_banner', models.ImageField(blank=True, null=True, upload_to='drivers/brand_banners/')),
                ('advertising_active', models.BooleanField(default=False)),
                ('advertising_description', models.TextField(blank=True, null=True)),
                ('advertising_license_copy', models.ImageField(blank=True, null=True, upload_to='drivers/brand_licenses/')),
                ('share_location', models.BooleanField(default=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل راننده',
                'verbose_name_plural': 'پروفایل رانندگان',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=11)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('VERIFY_PROFILE', 'Verify profile step')], default='LOGIN', max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'indexes': [models.Index(fields=['identifier', 'purpose', 'used'], name='accounts_ot_identif_23827b_idx')],
            },
        ),
    ]
