# Generated by Django 5.2.14 on 2026-05-10 03:19

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='kyc_updated_at',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_copy',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_expire_date',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='national_id_image',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='selfie_with_id',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_document_copy',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_insurance_copy',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID_FRONT', 'National ID Front'), ('NATIONAL_ID_BACK', 'National ID Back'), ('DRIVING_LICENSE', 'Driving License'), ('VEHICLE_REGISTRATION', 'Vehicle Registration')], max_length=50)),
                ('file', models.ImageField(blank=True, null=True, upload_to=utils.upload_document_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
