# Generated by Django 5.2.14 on 2026-05-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_driverprofile_kyc_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='brand_banner',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='brand_description',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='advertising_active',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='advertising_description',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='advertising_license_copy',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='brand_banner',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_plate',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_plate_image',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_year',
        ),
    ]
