# Generated by Django 5.2.14 on 2026-05-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_clientprofile_brand_banner_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='advertiser_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('LEGAL', 'Legal')], default='REAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id_or_registration_copy',
            field=models.ImageField(blank=True, null=True, upload_to='clients/kyc_docs/False'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
