# Generated by Django 5.2.14 on 2026-05-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driverprofile_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('DRIVER', 'Driver'), ('PRINT_SHOP', 'Print Shop')], default='CLIENT', max_length=10),
        ),
    ]
