# Generated by Django 5.2.14 on 2026-05-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('geo', '0001_initial'),
        ('print_shops', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignarea',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_areas', to='geo.city'),
        ),
        migrations.AddField(
            model_name='campaignarea',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_areas', to='geo.neighborhood'),
        ),
        migrations.AddField(
            model_name='campaignarea',
            name='suggested_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_areas', to='geo.suggestedroute'),
        ),
        migrations.AddField(
            model_name='campaigndesign',
            name='banner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.bannertype'),
        ),
        migrations.AddField(
            model_name='campaigndesign',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigndesign',
            name='print_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_designs', to='print_shops.printshopprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaigngoal'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignsetting',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignsetting',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='vehicles.vehicletype'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='campaigns.campaigninvoice'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='campaign_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='campaigns.campaigndesign'),
        ),
        migrations.AddField(
            model_name='campaigndesign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_designs', to='campaigns.template'),
        ),
    ]
