# Generated by Django 5.2.14 on 2026-05-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaigninvoice_campaign'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninvoice',
            name='modification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='modification_type',
            field=models.CharField(blank=True, choices=[('EXTEND', 'تمدید کمپین'), ('ADD_VEHICLES', 'افزایش خودرو'), ('CHANGE_DESIGN', 'تغییر بنر')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CampaignPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active_days', models.PositiveIntegerField()),
                ('hours_per_day', models.PositiveIntegerField()),
                ('max_driver', models.PositiveIntegerField()),
                ('design_type', models.CharField(choices=[('user_upload', 'User Upload'), ('custom_design', 'Custom Design'), ('default_template', 'Default Template')], default='DEFAULT_TEMPLATE', max_length=30)),
                ('area_type', models.CharField(choices=[('CIRCLE', 'Circle'), ('SUGGESTED_ROUTE', 'Suggested Route'), ('FREE_AREA', 'Free Area')], default='CIRCLE', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.bannertype')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicletype')),
            ],
        ),
    ]
