# Generated by Django 5.2.14 on 2026-06-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaigninvoice_modification_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndesign',
            name='design_type',
            field=models.CharField(choices=[('USER_UPLOAD', 'User Upload'), ('CUSTOM_DESIGN', 'Custom Design'), ('DEFAULT_TEMPLATE', 'Default Template')], max_length=30),
        ),
        migrations.AlterField(
            model_name='campaignpackage',
            name='design_type',
            field=models.CharField(choices=[('USER_UPLOAD', 'User Upload'), ('CUSTOM_DESIGN', 'Custom Design'), ('DEFAULT_TEMPLATE', 'Default Template')], default='DEFAULT_TEMPLATE', max_length=30),
        ),
    ]
