# Generated by Django 5.2.14 on 2026-06-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaigndesign_design_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignarea',
            name='radius_meter',
            field=models.PositiveIntegerField(blank=True, default=5000, help_text='شعاع دایره به متر (مقدار ثابت)', null=True),
        ),
    ]
