# Generated by Django 5.2.14 on 2026-05-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_active_seconds', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_distance_km', models.FloatField(blank=True, default=0.0, null=True)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='درآمد محاسبه\u200cشده توسط سرویس خارجی', max_digits=12, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict, null=True)),
                ('sticker_image', models.ImageField(blank=True, null=True, upload_to='trips/installations/')),
                ('driver_car_image', models.ImageField(blank=True, null=True, upload_to='trips/installations/')),
                ('installation_verified', models.BooleanField(default=False)),
                ('installation_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='campaigns.campaign')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driverprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TripAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('exposure_score', models.FloatField(default=0.0)),
                ('estimated_impressions', models.FloatField(default=0.0)),
                ('data_quality', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('avg_traffic_ratio', models.FloatField(default=0.0)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('analysis_run_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('night_factor', models.FloatField(default=1.0)),
                ('long_stop_factor', models.FloatField(default=1.0)),
                ('suspicious_stop_penalty', models.FloatField(default=0.0)),
                ('invalid_data_penalty', models.FloatField(default=0.0)),
                ('total_penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='trips.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', '-created_at'], name='trips_trip_driver__1c1019_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['COMPLETED', 'CANCELLED']), _negated=True), fields=('driver',), name='unique_active_trip_per_driver'),
        ),
    ]
