# Generated by Django 5.2.14 on 2026-05-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('exposure_score', models.FloatField(default=0.0)),
                ('estimated_impressions', models.FloatField(default=0.0)),
                ('data_quality', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('avg_traffic_ratio', models.FloatField(default=0.0)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('analysis_run_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='trips.trip')),
            ],
        ),
    ]
