# Generated by Django 5.2.14 on 2026-05-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driverprofile_vehicle_type_and_more'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.driverprofile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='درآمد محاسبه\u200cشده توسط سرویس خارجی', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_active_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_distance_km',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle'),
        ),
    ]
