# Generated by Django 5.2.14 on 2026-05-30 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_hourlyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='feedback',
            field=models.TextField(blank=True, help_text='بازخورد مشتری', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='امتیاز مشتری (۱ تا ۵)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
