# Generated by Django 5.2.14 on 2026-05-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_car_image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/installations/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='installation_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='installation_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='sticker_image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/installations/'),
        ),
        migrations.AddField(
            model_name='tripanalysis',
            name='invalid_data_penalty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tripanalysis',
            name='long_stop_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tripanalysis',
            name='night_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tripanalysis',
            name='suspicious_stop_penalty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tripanalysis',
            name='total_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
