# Generated by Django 5.2.14 on 2026-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='kyc_step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'انتخاب نوع فعالیت'), (2, 'بارگذاری مدارک'), (3, 'در انتظار تأیید'), (4, 'تأیید شده'), (5, 'رد شده')], default=1),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='advertiser_type',
            field=models.CharField(choices=[('REAL', 'حقیقی'), ('LEGAL', 'حقوقی')], default='REAL', max_length=10),
        ),
    ]
