# Generated by Django 5.2.14 on 2026-05-30 04:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField(help_text='ساعت شبانه\u200cروز (0 تا 23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('active_seconds', models.FloatField(default=0.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_activities', to='trips.trip')),
            ],
            options={
                'verbose_name': 'فعالیت ساعتی',
                'verbose_name_plural': 'فعالیت\u200cهای ساعتی',
                'unique_together': {('trip', 'hour')},
            },
        ),
    ]
