# Generated by Django 5.2.14 on 2026-05-29 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='drivers/avatars/')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reject_reason', models.TextField(blank=True, null=True)),
                ('registration_step', models.PositiveSmallIntegerField(choices=[(1, 'اطلاعات شخصی'), (2, 'بارگذاری مدارک'), (3, 'احراز هویت'), (4, 'قرارداد')], default=1)),
                ('is_contract_accepted', models.BooleanField(default=False)),
                ('share_location', models.BooleanField(default=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد معرف')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پروفایل راننده',
                'verbose_name_plural': 'پروفایل رانندگان',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PROFILE_PICTURE', 'عکس پروفایل'), ('DRIVING_LICENSE', 'گواهینامه'), ('VEHICLE_CARD', 'کارت خودرو'), ('GREEN_SHEET', 'برگه سبز')], max_length=30)),
                ('file', models.FileField(upload_to='drivers/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
