# Generated by Django 5.2.14 on 2026-05-21 02:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID_FRONT', 'National ID Front'), ('NATIONAL_ID_BACK', 'National ID Back'), ('DRIVING_LICENSE', 'Driving License'), ('VEHICLE_REGISTRATION', 'Vehicle Registration')], max_length=50)),
                ('file', models.ImageField(blank=True, null=True, upload_to=utils.upload_document_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(blank=True, help_text='برای حقیقی: کد ملی ۱۰ رقمی', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد ملی باید ۱۰ رقمی باشد.')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='drivers/avatars/')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reject_reason', models.TextField(blank=True, null=True)),
                ('share_location', models.BooleanField(default=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل راننده',
                'verbose_name_plural': 'پروفایل رانندگان',
            },
        ),
    ]
