# Generated by Django 5.2.14 on 2026-05-21 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID_FRONT', 'National ID Front'), ('NATIONAL_ID_BACK', 'National ID Back'), ('DRIVING_LICENSE', 'Driving License'), ('VEHICLE_REGISTRATION', 'Vehicle Registration')], max_length=30),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='file',
            field=models.FileField(default=b'default_content', upload_to='drivers/documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد ملی باید ۱۰ رقمی باشد.')]),
        ),
    ]
