# Generated by Django 5.2.14 on 2026-05-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_driverprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
