# Generated by Django 5.2.14 on 2026-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_driverprofile_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
