# Generated by Django 5.2.14 on 2026-05-27 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverdocument_processed'),
        ('geo', '0002_driverlocation_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdocument',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='geo.city'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_contract_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='registration_step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'اطلاعات شخصی'), (2, 'بارگذاری مدارک'), (3, 'احراز هویت'), (4, 'قرارداد')], default=1),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_type',
            field=models.CharField(choices=[('PROFILE_PICTURE', 'عکس پروفایل'), ('DRIVING_LICENSE', 'گواهینامه'), ('VEHICLE_CARD', 'کارت خودرو'), ('GREEN_SHEET', 'برگه سبز')], max_length=30),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
