# Generated by Django 5.2.14 on 2026-05-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_remove_driverdocument_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد معرف'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='drivers.driverprofile', verbose_name='دعوت\u200cشده توسط'),
        ),
    ]
