# Generated by Django 5.2.14 on 2026-05-18 15:20

import campaigns.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_driverprofile_vehicle_type_and_more'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_count', models.PositiveIntegerField(default=1)),
                ('days_count', models.PositiveIntegerField(default=1)),
                ('hours_per_day', models.PositiveIntegerField(default=1)),
                ('design_type', models.CharField(blank=True, max_length=30, null=True)),
                ('area_type', models.CharField(blank=True, max_length=30, null=True)),
                ('subtotal_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIGURING', 'Configuring'), ('READY_FOR_PAYMENT', 'Ready For Payment'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=30)),
                ('payment_expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('EXECUTION', 'Execution'), ('DESIGN', 'Design'), ('AREA', 'Area'), ('DISCOUNT', 'Discount'), ('TAX', 'Tax')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_type', models.CharField(choices=[('user_upload', 'User Upload'), ('custom_design', 'Custom Design'), ('default_template', 'Default Template')], max_length=30)),
                ('user_uploaded_file', models.FileField(blank=True, null=True, upload_to='campaign/designs/user/')),
                ('final_design_file', models.FileField(blank=True, null=True, upload_to='campaign/designs/final/')),
                ('logo_brand', models.FileField(blank=True, null=True, upload_to='campaign/designs/logo_brand/')),
                ('designer_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In_Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('VOID', 'Void')], max_length=20)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('DECIMAL', 'Decimal'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('TEXT', 'Text'), ('JSON', 'JSON')], default='DECIMAL', max_length=20)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=500, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_days', models.PositiveIntegerField()),
                ('activity_hours_per_day', models.TimeField()),
                ('max_driver', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=campaigns.models.product_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=50, unique=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_FOR_DESIGN', 'Waiting For Design'), ('WAITING_FOR_PAYMENT', 'Waiting For Payment'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='brands.brand')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('CIRCLE', 'Circle'), ('SUGGESTED_ROUTE', 'Suggested Route'), ('FREE_AREA', 'Free Area')], max_length=30)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius_meter', models.PositiveIntegerField(blank=True, null=True)),
                ('region_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='campaigns.campaign')),
            ],
        ),
    ]
