# Generated by Django 5.2.14 on 2026-05-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsetting',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='campaigns.campaign'),
        ),
    ]
