# Generated by Django 5.2.14 on 2026-05-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaignsetting_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignsetting',
            old_name='max_driver',
            new_name='max_drivers',
        ),
    ]
