# Generated by Django 5.2.14 on 2026-05-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_max_driver_campaignsetting_max_drivers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignsetting',
            old_name='max_drivers',
            new_name='max_driver',
        ),
    ]
