# Generated by Django 5.2.14 on 2026-05-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_end_date_alter_campaign_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndesign',
            name='estimated_ready_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
