# Generated by Django 5.2.14 on 2026-05-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaigndesign_estimated_ready_date'),
        ('print_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndesign',
            name='print_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_designs', to='print_shops.printshopprofile'),
        ),
        migrations.AddField(
            model_name='campaigndesign',
            name='print_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready for Pickup'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
    ]
