# Generated by Django 5.2.14 on 2026-05-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='source',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('batch', 'Batch')], default='realtime', help_text='نحوه دریافت موقعیت', max_length=10),
        ),
    ]
