# Generated by Django 5.2.14 on 2026-05-29 17:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('COMPANY_REGISTRATION', 'Company Registration'), ('ADVERTISING_LICENSE', 'Advertising License'), ('TAX_CERTIFICATE', 'Tax Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='clients/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_type', models.CharField(choices=[('REAL', 'Real'), ('LEGAL', 'Legal')], default='REAL', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('national_id', models.CharField(blank=True, help_text='برای حقیقی: کد ملی ۱۰ رقمی', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد ملی باید ۱۰ رقمی باشد.')])),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('national_economic_code', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clients/avatars/')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('kyc_reject_reason', models.TextField(blank=True, null=True)),
                ('kyc_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_advertising_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
