# Generated by Django 5.2.14 on 2026-05-21 02:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_type', models.CharField(choices=[('REAL', 'Real'), ('LEGAL', 'Legal')], default='REAL', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('national_id', models.CharField(blank=True, help_text='برای حقیقی: کد ملی ۱۰ رقمی', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد ملی باید ۱۰ رقمی باشد.')])),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('national_economic_code', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clients/avatars/')),
                ('id_or_registration_copy', models.ImageField(blank=True, null=True, upload_to='clients/kyc_docs/False')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('kyc_reject_reason', models.TextField(blank=True, null=True)),
                ('kyc_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_ad_image', models.ImageField(blank=True, null=True, upload_to='clients/ads/primary_images/')),
                ('primary_ad_banner', models.ImageField(blank=True, null=True, upload_to='clients/ads/primary_banners/')),
                ('advertising_description', models.TextField(blank=True, null=True)),
                ('advertising_license_copy', models.ImageField(blank=True, null=True, upload_to='clients/ads/licenses/')),
                ('is_advertising_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
