# Generated by Django 5.2.14 on 2026-05-21 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='advertising_description',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='advertising_license_copy',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='id_or_registration_copy',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='primary_ad_banner',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='primary_ad_image',
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('COMPANY_REGISTRATION', 'Company Registration'), ('ADVERTISING_LICENSE', 'Advertising License'), ('TAX_CERTIFICATE', 'Tax Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='clients/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
