# Generated by Django 5.2.14 on 2026-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clientprofile_advertising_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
