# Generated by Django 5.2.14 on 2026-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_kyc_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID_FRONT', 'روی کارت ملی'), ('NATIONAL_ID_BACK', 'پشت کارت ملی'), ('SELFIE', 'عکس سلفی'), ('BUSINESS_LICENSE', 'گواهی کسب'), ('ECONOMIC_CODE', 'کد اقتصادی'), ('OTHER', 'سایر')], max_length=30),
        ),
    ]
