# Generated by Django 5.2.14 on 2026-05-30 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontent',
            name='type',
            field=models.CharField(choices=[('CONTACT', 'تماس با ما'), ('FAQ', 'سوالات متداول'), ('RULES', 'قوانین و مقررات شهری')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
