# Generated by Django 5.2.14 on 2026-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportcontent_type_alter_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ANDROID', 'اندروید'), ('IOS', 'iOS'), ('PWA', 'وب اپلیکیشن')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لینک دانلود',
                'verbose_name_plural': 'لینک\u200cهای دانلود',
                'unique_together': {('platform', 'version')},
            },
        ),
    ]
